experiment:
  name: teste_modelos_todas_as_variaveis
  scenario: salary_negotiation
  turn_delay_seconds: 10
  max_turns: 7
  use_system_reminder: true
context:
  enabled: true
  inflation: LOW
  interest_rates: LOW
  government: MARKET_FRIENDLY
  crises:
  - FINANCIAL_CRISIS
  gdp_growth: Growing
  unemployment: Falling rates, growing labor market.
  custom_conditions: null
models:
  agent_1:
    provider: ollama
    name: gemma4:31b-cloud
    temperature: 0.5
    max_tokens: 2048
    persona:
      agreeableness: positive
      neuroticism: positive
      extraversion: positive
      openness: positive
      conscientiousness: positive
      extra_instructions: You will not accept just any offer. You are an engineer
        with over 20 years of experience
    tactics:
      anchoring: 5
      conditional_concession: 2
      value_creation: 4
      clarity: 4
      loss_aversion: 1
      fact_justification: 5
    utility:
      p_target: 3600
      p_floor: 3100
  agent_2:
    provider: gemini
    name: gemma-4-26b-a4b-it
    temperature: 0.5
    max_tokens: 2048
    persona:
      agreeableness: positive
      neuroticism: positive
      extraversion: positive
      openness: positive
      conscientiousness: positive
      extra_instructions: You have carte blanche to raise salaries and benefits for
        whoever you are hiring
    tactics:
      anchoring: 2
      conditional_concession: 4
      value_creation: 5
      clarity: 4
      loss_aversion: 2
      fact_justification: 5
    utility:
      p_target: 2800
      p_floor: 3300
  judge:
    provider: ollama
    name: gpt-oss:120b-cloud
    temperature: 0.0
    metrics:
    - agreeableness
    - neuroticism
    - extraversion
    - openness
    - conscientiousness
    - anchoring
    - conditional_concession
    - value_creation
    - clarity
    - loss_aversion
    - fact_justification
