experiment:
  name: "teste_agreeableness"
  scenario: "salary_negotiation"
  turn_delay_seconds: 2
  max_turns: 5
  use_system_reminder: true

# Define a pressão do mundo externo
context:
  enabled: true
  inflation: "HIGH"
  interest_rates: "VERY_HIGH"
  government: "INTERVENTIONIST"
  crises:
    - "ECONOMIC_RECESSION"
    - "POLITICAL_INSTABILITY"
  country: "Brazil"
  year: "2025"
  custom_conditions:

# Dá para adicionar o efeito âncora pela extra_instuctions acima
# E também dá para adicionar instruções separadas para cada agente
# As condições de necessidade, devem existir para ambos que negociam. inclusive podem ser distintas
# digo pode ter condição global para ambos
models:
  # Primeira role
  agent_1:
    provider: "lmstudio"
    name: "google/gemma-4-e2b"
    temperature: 0.5
    max_tokens: 2048
    persona:
      #agreeableness: 3
      #neuroticism: 0
      #extraversion: 0
      openness: 3
      #conscientiousness: 3
      extra_instructions: "Sua empresa (varejo) está sofrendo muito com a recessão. Você TEM que conseguir um desconto agressivo no software ou o projeto será cancelado. Jogue duro e não aceite a primeira oferta."
    tatics:
      #anchoring: 5
      #conditional_concession: 3
      #value_creation: 2
      #rapport: 5
      #resilience: 4
      #clarity: 4
      #anchor_susceptibility: 3
      #loss_aversion: 1
      #fact_justification: 5

  # Segunda role
  agent_2:
    provider: "lmstudio"
    name: "google/gemma-4-e2b"
    temperature: 0.5
    max_tokens: 2048
    persona:
      #agreeableness: 3
      #neuroticism: 0
      #extraversion: 0
      #openness: 3
      #conscientiousness: 3
      extra_instructions: "Você precisa bater sua meta de vendas do trimestre. Seja empático, tente construir relacionamento, mas use concessões condicionais: só diminua o preço se o cliente abrir mão de algo."
    tatics:
      #anchoring: 2
      #conditional_concession: 4
      #value_creation: 5
      #rapport: 5
      #resilience: 4
      #clarity: 4
      #anchor_susceptibility: 3
      #loss_aversion: 3
      #fact_justification: 5

  judge:
    provider: "ollama"
    name: "gpt-oss:120b-cloud"
    temperature: 0.0
    metrics:
      - "agreeableness"
      - "neuroticism"
      - "extraversion"
      - "openness"
      - "conscientiousness"
      - "anchoring"
      - "conditional_concession"
      - "value_creation"
      - "rapport"
      - "resilience"
      - "clarity"
      - "anchor_susceptibility"
      - "loss_aversion"
      - "fact_justification"
#deepseek-v4-pro:cloud
